### ISSUE TITLE
Menu problem

### ISSUE THREAD

**Issue by pedromorgan** [key-amb/hugo-theme-bootie-docs#22]
Am a hugo newbie, so this might be a muppet question..

Reading about menus here..https://gohugo.io/extras/menus/

Vs the details in README.md seem different.

ie 
```yaml
menu:
  main:
     - name: Home
    .....

vs

params:
   mainMenu:
    - name: Home
```
Which one is more correct ?
